[project]
name = "my_project"
version = "0.1.0"
description = "Update pyproject.toml to fit your needs."
authors = [
    {name = "UncleThaodan", email = "sample@email.fake"},
]
license-expression = "MIT"
dependencies = []
requires-python = ">=3.9"
readme = "README.md"

classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
]

[project.scripts]
run-my-project = "my_project.main:start"

[project.urls]
Repository = "https://github.com/UncleThaodan/dpm-cli-example"

[tool.pdm]

[build-system]
requires = ["pdm-pep517>=0.12.0"]
build-backend = "pdm.pep517.api"
